### ISSUE TITLE
Please include builds

### ISSUE THREAD

**Issue by LuigiXHero** [fuzziqersoftware/gctools#2]
As names imply, I think including builds would make it easier for people to use and therefore beta test the programs. I really don't want to bloat my computer with a bunch of programs just to build one set of programs. Which seems to be a issue with most gamecube tools.

**Comment by TurtleTrademark** [comment]
^ agreed, life would be so much better if you just included the builded version.

**Comment by fuzziqersoftware** [comment]
I've uploaded Windows and macOS builds at https://github.com/fuzziqersoftware/gctools/releases. The Windows builds are a bit old but should be reasonably functional; I did not rebuild master on Windows since I don't have a sufficiently accessible Windows machine handy.

**Comment by TurtleTrademark** [comment]
> 
> 
> I've uploaded Windows and macOS builds at https://github.com/fuzziqersoftware/gctools/releases. The Windows builds are a bit old but should be reasonably functional; I did not rebuild master on Windows since I don't have a sufficiently accessible Windows machine handy.

thank you.
