### ISSUE TITLE
Outdated README.md?

### ISSUE THREAD

**Issue by OoLunar** [fuzziqersoftware/gctools#4]
Hello!

I have compiled gctools without issue. I'm attempting to extract the `res/Object/*` arc files (which I have reason to believe that these are the models) from Twilight Princess. In your README, specifically in [this section](https://github.com/fuzziqersoftware/gctools#getting-files-from-the-legend-of-zelda-twilight-princess), you use the tool `rarcdump`. Now, I'm not seeing `rarcdump` in gctool's arsenal, so I'm wondering how you got the executable.

With much appreciation for your project,
- Lunar

**Comment by fuzziqersoftware** [comment]
rarcdump isn't part of gctools; you can find it [here, as part of szstools](http://amnoid.de/gc/). I'll update the readme with this link.

**Comment by OoLunar** [comment]
Much appreciated
